/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FetchError: typeof import('./src/components/api/FetchError/FetchError.vue')['default']
    Fetching: (typeof import('./src/components/api/FetchingIndicator.vue'))['default']
    FetchingIndicator: typeof import('./src/components/api/FetchingIndicator.vue')['default']
    FetchWrapper: typeof import('./src/components/api/FetchWrapper/FetchWrapper.vue')['default']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
  }
}
